# Generated by Django 5.0.7 on 2024-07-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='PerevalLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=20)),
                ('summer', models.CharField(blank=True, max_length=20)),
                ('autumn', models.CharField(blank=True, max_length=20)),
                ('spring', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'pereval_levels',
            },
        ),
        migrations.CreateModel(
            name='PerevalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pereval_users',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beautyTitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('other_titles', models.CharField(max_length=200)),
                ('connect', models.CharField(max_length=200, null=True)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalcoords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevallevels')),
            ],
            options={
                'db_table': 'pereval',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='pereval_images/')),
                ('pereval', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.pereval')),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.AddConstraint(
            model_name='perevalusers',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_phone'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalusers'),
        ),
    ]
