# Generated by Django 5.0.7 on 2024-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pereval_date_added_alter_pereval_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('pending', 'в ожидании'), ('confirmed', 'подтверждена'), ('rejected', 'отклонена')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='image',
            field=models.ImageField(null=True, upload_to='pereval_images/'),
        ),
        migrations.AlterField(
            model_name='perevallevels',
            name='autumn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perevallevels',
            name='spring',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perevallevels',
            name='summer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perevallevels',
            name='winter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
