# Generated by Django 5.0.7 on 2024-07-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pereval_status_alter_perevalimages_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='beautyTitle',
            new_name='beauty_title',
        ),
        migrations.RenameField(
            model_name='pereval',
            old_name='coord',
            new_name='coords',
        ),
    ]
