# Generated by Django 5.0.7 on 2024-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_beautytitle_pereval_beauty_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalimages',
            old_name='image',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='perevallevels',
            name='winter',
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
