# Generated by Django 5.0.7 on 2024-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_perevalimages_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='pereval_images/'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
