# Generated by Django 5.0.7 on 2024-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pereval_connect_alter_perevalimages_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevallevels',
            name='winter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
