# Generated by Django 5.0.7 on 2024-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_perevalimages_data_alter_perevalimages_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='data',
            field=models.ImageField(null=True, upload_to='project\\media'),
        ),
    ]
