# Generated by Django 5.0.7 on 2024-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_perevalimages_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='project\\media'),
        ),
    ]
